### PR TITLE
Obligations event response JSON schema

### PR DESCRIPTION
**Pull request by anweiss**
Adding a JSON schema for the obligations event response model as described in https://github.com/PM-Master/policy-machine-core/blob/master/src/main/java/gov/nist/csd/pm/pip/obligations/README.md. Based on JSON schema Draft 07. CC @joshua-roberts for review

### CODE REVIEW

**Comment by joshua-roberts** [comment]
Awesome, thank you for doing this. I just have a few questions before merging. 

1. We allow custom events (see https://github.com/PM-Master/policy-machine-core#custom-events).  Is it possible for any user creating a custom event to just define the schema for their event and then use that in conjunction with this one?
2. Users can specify custom operations in the default event syntax. So operations aren't necessarily restricted to the ones in Operations.  Could we just define operations as an array of string instead of enum? 
3. Users can define custom functions in the response.  Similar to (1) would they just need to define a schema for their function and use it with this one?

Thanks!

**Comment by anweiss** [comment]
1. Indeed, custom events can be defined by separate schemas and `"$ref"`'ed back to the main schema.
2. Good catch. I'll update the `#/definitions/operation` definition to allow for additional custom values outside of the enum.
3. Yes, they can define their own custom function schemas for the response and `"$ref"` them back to the main schema.

**Comment by anweiss** [comment]
Also, I just realized that I need to update the built-in function validation logic. Standby before merging.

**Comment by anweiss** [comment]
@joshua-roberts I've updated the schema to reflect your comments. I've also added descriptions and cleaned up some of the built-in function validation logic. Let me know if something seems off. Thanks!

**Pull request merged**
